### ISSUE TITLE
UI wireframes

### ISSUE THREAD

**Issue by b0g3r** [PiterPy-Meetup/postpost-frontend#1]

**Comment by b0g3r** [comment]
@obuhhh подошьёшь исходники/выгрузку сюда?

**Comment by obuhhh** [comment]
https://www.figma.com/file/OSdFuqMzdgs3LCzc1b1BJpW2/PostPost?node-id=0%3A1

**Comment by b0g3r** [comment]
@obuhhh спасибо, диз <3
